### ISSUE TITLE
Fail to parse native fetch error in Chrome

### ISSUE THREAD

**Issue by dariocravero** [stacktracejs/error-stack-parser#26]
Hi,

`error-stack-parser` seems to fail to recognise native fetch errors.
The error doesn't seem to have a recognisable stack, so unless I wrap it with `Error` it fails.

Here's [a demo project](http://uxtemple.github.io/error-stack-parser-fetch/public/) to show the issue and the [source](https://github.com/UXtemple/error-stack-parser-fetch). Hope that helps :).

The test was done on Chrome Version 47.0.2526.73 beta (64-bit) in Mac OS X El Capitan.

Thanks!
Darío

**Comment by eriwen** [comment]
This is a really well-done bug report :)

The Error `stack` being captured by `.catch(err)` is just `"SyntaxError: Unexpected token <"` which doesn't have any information to parse. 

I find it curious that the V8 stack is so incomplete because one of the touted features of Promises is to keep stack traces intact across asynchronous code. Perhaps there's a different usage of `fetch()` that somehow produces a trace

**Comment by dariocravero** [comment]
Glad it helped :). It is a tricky one indeed :/. Let's dive into [Twitter's wisdom](https://twitter.com/dariocravero/status/673286431956160514) :)

**Comment by domenic** [comment]
This seems pretty straightforward.

When a fetch error occurs, no author code is on the stack. The browser is off in networking land. It then posts back to the main thread saying "reject the promise with a new Error. I have no stack trace information for that error since I am creating it in the network thread, and there is no author code on the stack in the network thread."

If you use developer tools, you can get async stack traces, where the browser actually knows you have opted in to a slow debugging mode, so every time you do something async, it tracks it. E.g., he is starting a fetch with a stack of author code X. So if that fetch ever errors, attach recorded stack X to it in devtools. But that's a separate thing from `error.stack`, which gives the stack of author code at the time the error occurred---and there is none, there.

**Comment by eriwen** [comment]
Thank you for explaining, @domenic. I wasn't aware that this Error was being generated from the network thread. 

It would be useful if developers had a way of enabling this stack tagging outside of DevTools. 

Thanks again for your time. 

@dariocravero Given Domenic's answer, I'm not sure what we can do in this library to help. If you agree, then we can close this issue.

**Comment by dariocravero** [comment]
Hi @eriwen, please, go ahead and close it. I'll may end up wrapping those into `Error` from now on so that the lib doesn't trip on them. Thanks both for your time :)
